import 'dotenv/config'
import { migrate } from 'drizzle-orm/postgres-js/migrator'
import { db } from './db'

const runMigrations = async () => {
  console.log('⏳ Running migrations...')
  
  try {
    // This looks for migrations in the drizzle folder generated by drizzle-kit
    // This looks for migrations in the folder generated by drizzle-kit
    await migrate(db, { migrationsFolder: './server/database/migrations' })
    console.log('✅ Migrations completed successfully')
  } catch (error) {
    console.error('❌ Migration failed:', error)
    process.exit(1)
  }
}

runMigrations()
